### ISSUE TITLE
protobuf-dt not working in eclipse mars

### ISSUE THREAD

**Issue by Jack2code** [google/protobuf-dt#1]
```
#protobuf-dt
Protocol Buffer Editor --  2.2.1.201601041517
Xtext Runtime -- 2.9.1.v201512180746

#eclipse
eclipse version:Mars.2 Release(4.5.2)
Build id:20160218-0600

#os
Ubuntu 14.04 x86_64

#protoc
libprotoc 2.5.0
```

I install the protobuf-dt by Eclipse Marketplace. And then restart eclipse. 

But open the .proto file in editor, it won't be highlights. In the menu of project properties, can not find "Probotocol Buffer".

Any ideas,pls?

**Comment by atrookey** [comment]
Does syntax highlighting work when you create a new protobuf file instead of opening an existing one? Please navigate to the new file wizard (File > New > Other) and let me know if the category "Protocol Buffer" is among those listed.

**Comment by Jack2code** [comment]
@atrookey I'm sorry, but the category "Protocol Buffer" does not exist.

syntax highlighting not working whether I create a new protobuf file or opening an existing one.

**Comment by atrookey** [comment]
I think the Eclipse Marketplace may have failed.  May you please try installing the protobuf editor manually following the instructions here: https://protobuf-dt.googlesource.com/protobuf/#Installing-protobuf_dt ?

**Comment by Jack2code** [comment]
@atrookey I'm sorry, but still not working by installing it manually.

**Comment by atrookey** [comment]
@Jack2code I have been unable to reproduce the bug on my Mac OS X or Linux running Eclipse Mars.  You could try upgrading to the latest version of Eclipse, Neon, and see if it works then.

**Comment by atrookey** [comment]
@Jack2code I added the latest version of the protocol bufferer editor to the update site, http://google.github.io/protobuf-dt/updates/latest/ (the link will not work in the browser).  Perhaps the latest version of the editor will install successfully.
