### ISSUE TITLE
"import" handled differently between protobuf-dt and the maven plugin?

### ISSUE THREAD

**Issue by jhberges** [google/protobuf-dt#6]
Greetings!

Given the setup:

     /
     +- some_global_include.proto
     +- /some_artifact/
         +- some_artifact.proto

The maven plugin will accept (in `some_artifact.proto`):

    import "some_global_include.proto";

And the protobuf-dt plugin will accept:

    import "../some_global_include.proto";

They appear to be mutually exclusive, as far as I've found.

I could live with an option in the Eclipse plugin to list the directories to include - maybe there even is one already? :-)

**Comment by atrookey** [comment]
Hi jhberges, I'm not familiar with how the maven plugin works.  I'm curious which form the [protobuf compiler](https://github.com/google/protobuf) accepts.  If it is the case that it accepts the first form, then the protobuf editor will have to be fixed.

**Comment by sprigogin** [comment]
> I could live with an option in the Eclipse plugin to list the directories to include - maybe there even
> is one already?

Directories to include can be specified in Project > Properties > Protocol Buffer > Import Paths.

**Comment by jhberges** [comment]
Ah! Thanks @sprigogin ! :+1:
